image: python:3.11

stages:
  - test

variables:
  CFLAGS: "-Wall -Werror"
  CXXFLAGS: "-Wall -Werror"

before_script:
  - apt-get update
  - apt-get install -y gcc g++ make
  - pip install cantools

test_pipeline:
  stage: test
  script:
    - python3 test_apps/test_pipeline.py