name: Build, Run and Release Python App

on:
  push:
    tags:
      - 'v*'

jobs:
  set_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: extract
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  build-windows:
    runs-on: windows-latest
    needs: set_version
    env:
      APP_VERSION: ${{ needs.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Briefcase and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase
          pip install -r requirements.txt

      - name: Inject version into __main__.py
        shell: pwsh
        run: |
          (Get-Content src/can_library_generator/__main__.py) -replace '__version__ = .*', '__version__ = "${{ env.APP_VERSION }}"' | Set-Content src/can_library_generator/__main__.py

      - name: Build Windows app with Briefcase
        run: |
          briefcase create windows
          briefcase build windows
          briefcase package windows

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.msi
            build/can_library_generator/windows/app/src/*.exe

  build-macos:
    runs-on: macos-latest
    needs: set_version
    env:
      APP_VERSION: ${{ needs.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Briefcase and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase
          pip install -r requirements.txt

      - name: Inject version into __main__.py
        run: |
          sed -i '' "s/^__version__ = .*/__version__ = \"${APP_VERSION}\"/" src/can_library_generator/__main__.py

      - name: Build macOS app with Briefcase
        run: |
          briefcase create macOS
          briefcase build macOS
          briefcase package macOS --adhoc-sign

      - name: Locate app bundle path
        id: locate_app
        run: |
          APP_PATH=$(find macOS/build -name "*.app" -type d | head -n 1)
          echo "path=$APP_PATH" >> "$GITHUB_OUTPUT"

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/CAN_Library_Generator.dmg

  build-linux:
    runs-on: ubuntu-latest
    needs: set_version
    env:
      APP_VERSION: ${{ needs.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdk-pixbuf2.0-0 libglib2.0-0 libxkbcommon-x11-0

      - name: Install Briefcase and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase
          pip install -r requirements.txt

      - name: Inject version into __main__.py
        run: |
          sed -i "s/^__version__ = .*/__version__ = \"${APP_VERSION}\"/" src/can_library_generator/__main__.py

      - name: Build Linux app with Briefcase
        run: |
          briefcase create linux
          briefcase build linux
          briefcase package linux

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.AppImage
            dist/*.deb
