name: Test CAN Library Generator

on:
  push:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CFLAGS: "-Wall -Werror"
      CXXFLAGS: "-Wall -Werror"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ make
          pip install -r requirements.txt

      - name: Run test pipeline script
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python3 src/test/test_pipeline.py
